name: test
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build_and_run_tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        go: [ "1.18.2" ]
        os: [ "ubuntu-20.04", "windows-2019", "macos-10.15" ]
    steps:
      - uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: "${{ matrix.go }}"
          cache-key-suffix: "-coverage-${{ matrix.go }}"
      - uses: actions/checkout@v2
      - run: go build -v ./...
      - run: go test -race ./...
